USE otmdb;

DROP TABLE IF EXISTS t_article;
DROP TABLE IF EXISTS t_comment;
DROP TABLE IF EXISTS t_user;

CREATE TABLE t_article (
	Guid VARCHAR(36) NOT NULL PRIMARY KEY,
	Title VARCHAR(128) NULL,
	Content VARCHAR(16000) NULL,
	IsPrivated TINYINT(1) DEFAULT 0,
	CreationDate DATETIME NOT NULL,
	Category VARCHAR(5) NOT NULL,
	LastModified DATETIME NULL,
	ViewsCount INT
	UNSIGNED DEFAULT 0
	-- FOREIGN KEY (Guid) REFERENCES t_comment(ArticleGuid)
) CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE t_comment (
	ID INT(10) NOT NULL UNIQUE AUTO_INCREMENT,
	Guid VARCHAR
	(36) NOT NULL PRIMARY KEY,
	Content VARCHAR
	(1024) NOT NULL,
	ArticleGuid VARCHAR
	(36) NOT NULL,
	CreationDate DATETIME NOT NULL,
	Author VARCHAR
	(128) NOT NULL,
	FOREIGN KEY
	(ArticleGuid) REFERENCES t_article
	(Guid) ON DELETE CASCADE ON UPDATE CASCADE
) CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE t_admin (
		Guid VARCHAR(36) NOT NULL PRIMARY KEY,
		SaltKey VARCHAR(255) NOT NULL,
		Password VARCHAR(255) NOT NULL,
		LastLogin DATETIME NULL
) CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;


CREATE TABLE t_user (
    Guid VARCHAR(36) NOT NULL PRIMARY KEY,
    Email VARCHAR(70) NOT NULL,
    SaltKey VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    LastLogin DATETIME NULL,
    Permission TINYINT(1) DEFAULT 0,
    Mobile VARCHAR(20)
) CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;